<a href="https://colab.research.google.com/github/daniyalshafique/Ai_Fall_2021/blob/main/Assign02_Naive_Bayes(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# -*- coding: utf-8 -*-
"""Assign02-Naive Bayes(1)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MlyvGkT4dfNreOQ95GlRz3ceZOklXjUa
"""

from google.colab import drive
# This will prompt for authorization.
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import sklearn
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer 	
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

train_data = pd.read_csv('/content/drive/MyDrive/train.csv')

train_data.head(5)

   Id  Elevation  Aspect  ...  Soil_Type39  Soil_Type40  Cover_Type
0   0       3189      40  ...            0            0           1
1   1       3026     182  ...            0            0           2
2   2       3106      13  ...            0            0           1
3   3       3022     276  ...            0            0           2
4   4       2906     186  ...            0            0           2

[5 rows x 56 columns]

In [3]:
train = pd.DataFrame(train_data)

y = train.Cover_Type
X = train.drop("Cover_Type", axis=1)

t_train, t_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=109)
print(t_train.head())
print(t_test.head())

              Id  Elevation  Aspect  ...  Soil_Type38  Soil_Type39  Soil_Type40
2233065  2233065       3274     140  ...            0            0            0
779053    779053       3054     128  ...            0            0            0
109067    109067       2724     277  ...            0            0            0
1076682  1076682       2758     268  ...            0            0            0
831485    831485       2850      94  ...            0            0            0

[5 rows x 55 columns]
              Id  Elevation  Aspect  ...  Soil_Type38  Soil_Type39  Soil_Type40
1385528  1385528       3353      16  ...            1            0            0
3530482  3530482       2711     158  ...            0            0            0
3048887  3048887       3356     325  ...            0            0            0
2151846  2151846       3004      52  ...            0            0            0
2169960  2169960       2989     311  ...            0            0            0

[5 rows x 55 columns]

In [4]:
clf = MultinomialNB(alpha = 0)
clf.fit(abs(t_train),y_train)
NoMNB = clf.score(t_test,y_test)
print("The Accuracy score of NoMNB", NoMNB*100)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:557: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  % _ALPHA_MIN

The Accuracy score of NoMNB 25.785375

In [5]:
# Using Leplace
clf = MultinomialNB(alpha = 1)
clf.fit(abs(t_train),y_train)
clf.fit(abs(t_train),y_train)
clf.predict(t_test)
LPMNB = clf.score(t_test,y_test)
print("The Accuracy Score of LPMNB", LPMNB*100)

The Accuracy Score of LPMNB 25.772499999999997

In [6]:
#Using LidStone
clf = MultinomialNB(alpha = 0.5)
clf.fit(abs(t_train),y_train)
clf.fit(abs(t_train),y_train)
clf.predict(t_test)
LDMNB = clf.score(t_test,y_test)
print("The Accuracy Score of LDMNB", LDMNB*100)

The Accuracy Score of LDMNB 25.754375000000003

In [7]:
test = pd.read_csv('/content/drive/MyDrive/test.csv')
test.head(5)

       id        f0        f1       f2  ...       f96       f97       f98       f99
0  600000  0.003229  4.838660  585.529  ...  0.290343  1.898200  0.131533  0.012047
1  600001  0.008602  0.505536 -100.099  ... -0.392923  3.689640  0.047418  0.120015
2  600002  1.461000  2.437260 -112.964  ...  4.054650  3.330670  0.108843  0.064687
3  600003  0.140556  3.085610  179.451  ...  2.696580 -0.533491  0.052524  0.011058
4  600004  0.128876  5.199760  107.466  ...  1.110710  3.584470  0.145319 -0.050393

[5 rows x 101 columns]